name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run cargo test and cargo build (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      
    - name: Run cargo test (CLI)
      run: cargo test --verbose
      
    - name: Run cargo build (CLI)
      run: cargo build --release --verbose
